# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: da90c97d7cf5a0b5ed290a205c4376c5f5673639054c30283708ae18585d7ff7de06895d9cc5fe8ec54d70287893fa5d11a45d7088e4530b54e09c9912d3b1f2

test:
  secret_key_base: 05587823cdfd83d1de9495206f2f22e5e56c0c57d9f387483a313cc642335408c9b99c54c294739015b88ec75364ef1226dcd716765ba5450a785d3331f5f722

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
